package com.mangofactory.pepper.model;
// default package
// Generated 26-Jun-2010 11:51:56 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * VoteType generated by hbm2java
 */
@Entity
@Table(name = "votetypes")
public class VoteType extends BaseEntity {

	private String name;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "voteType")
	private Set<Vote> votes = new HashSet<Vote>(0);

	public VoteType() {
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Vote> getVotes() {
		return this.votes;
	}

	public void setVotes(Set<Vote> votes) {
		this.votes = votes;
	}

}
