package com.mangofactory.pepper.model;
// default package
// Generated 26-Jun-2010 11:51:56 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PostType generated by hbm2java
 */
@Entity
@Table(name = "posttypes")
public class PostType extends BaseEntity {

	@Column(name = "Type", nullable = false, length = 10)
	private String type;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "postType")
	private Set<Post> posts = new HashSet<Post>(0);

	public PostType() {
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set<Post> getPosts() {
		return this.posts;
	}

	public void setPosts(Set<Post> posts) {
		this.posts = posts;
	}

}
