package com.mangofactory.pepper.model;
// default package
// Generated 26-Jun-2010 11:51:56 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vote generated by hbm2java
 */
@Entity
@Table(name = "votes")
public class Vote extends BaseEntity {

	@ManyToOne(fetch = FetchType.LAZY)
	private VoteType voteType;

	@ManyToOne(fetch = FetchType.LAZY)
	private Post post;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId")
	private User user;
	private Integer bountyAmount;
	private Date creationDate;

	public Vote() {
	}

	public VoteType getVoteType() {
		return this.voteType;
	}

	public void setVoteType(VoteType voteType) {
		this.voteType = voteType;
	}

	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "BountyAmount")
	public Integer getBountyAmount() {
		return this.bountyAmount;
	}

	public void setBountyAmount(Integer bountyAmount) {
		this.bountyAmount = bountyAmount;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
